import star from "../../assets/Star 2.png";
export const AllProducts = [
  {
    id: 4,
    title: "Mango    ",
    description: "Kimono & Caftan - Colorful - Night club fit",
    star: star,
    bgColor: { backgroundColor: "rgba(45,42,221,0.83)", borderRadius: "8px" },
    price: "$215",
    oldPrice: "$229",
    discount: "-10%",
  },
  {
    id: 3,
    title: "Uniqlo ",
    description: "Midi atlas Slim fit - bohemian",
    star: star,
    bgColor: { backgroundColor: "rgba(238,60,176,0.89)", borderRadius: "8px" },
    price: "$125",
    oldPrice: "$156",
    discount: "-8%",
  },
  {
    id: 2,
    title: "Zara ",
    description: "Midi top- Daily fit",
    star: star,
    bgColor: { backgroundColor: "rgba(95,35,206,0.9)", borderRadius: "8px" },
    price: "$95",
    oldPrice: "$145",
    discount: "-7%",
  },
  {
    id: 8,
    title: "Ralph Lauren ",
    description: "Blouse - Minimalist",
    star: star,
    bgColor: { backgroundColor: "rgba(184,34,207,0.81)", borderRadius: "8px" },
    price: "$68",
    oldPrice: "$89",
    discount: "-12%",
  },

  {
    id: 9,
    title: "NBB  ",
    description: "Bikini & seaside - Casual",
    star: star,
    bgColor: { backgroundColor: "rgba(98,13,13,0.86)", borderRadius: "8px" },
    price: "$300",
    oldPrice: "$365",
    discount: "-15%",
  },
  {
    id: 10,
    title: "Ralph Lauren ",
    description: "Dress - Beige - Shift - Casual",
    star: star,
    bgColor: { backgroundColor: "rgba(36,31,177,0.87)", borderRadius: "8px" },
    price: "$512",
    oldPrice: "$623",
    discount: "-20%",
  },

  {
    id: 1,
    title: "Ralph lauren ",
    description: "Shirt-oversize - Minimalist",
    star: star,
    bgColor: { backgroundColor: "rgba(115,33,165,0.9)", borderRadius: "8px" },
    price: "$259",
    oldPrice: "$356",
    discount: "-11%",
  },

  {
    id: 6,
    title: "Zara ",
    description: "Sweather - Black & White - Minimalist",
    star: star,
    bgColor: { backgroundColor: "rgba(186,37,37,0.8)", borderRadius: "8px" },
    price: "$365",
    oldPrice: "$487",
    discount: "-15%",
  },
  {
    id: 7,
    title: "Uniqlo ",
    description: "Sweather  - Casual",
    star: star,
    bgColor: { backgroundColor: "rgba(31,92,191,0.91)", borderRadius: "8px" },
    price: "$288",
    oldPrice: "$215",
    discount: "-10%",
  },
];
